// Code generated by ent, DO NOT EDIT.

package classreviewlike

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/yudai2929/kendai-navi/backend/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldUserID, v))
}

// ClassReviewID applies equality check predicate on the "class_review_id" field. It's identical to ClassReviewIDEQ.
func ClassReviewID(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldClassReviewID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldContainsFold(FieldUserID, v))
}

// ClassReviewIDEQ applies the EQ predicate on the "class_review_id" field.
func ClassReviewIDEQ(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldClassReviewID, v))
}

// ClassReviewIDNEQ applies the NEQ predicate on the "class_review_id" field.
func ClassReviewIDNEQ(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNEQ(FieldClassReviewID, v))
}

// ClassReviewIDIn applies the In predicate on the "class_review_id" field.
func ClassReviewIDIn(vs ...string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldIn(FieldClassReviewID, vs...))
}

// ClassReviewIDNotIn applies the NotIn predicate on the "class_review_id" field.
func ClassReviewIDNotIn(vs ...string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNotIn(FieldClassReviewID, vs...))
}

// ClassReviewIDGT applies the GT predicate on the "class_review_id" field.
func ClassReviewIDGT(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGT(FieldClassReviewID, v))
}

// ClassReviewIDGTE applies the GTE predicate on the "class_review_id" field.
func ClassReviewIDGTE(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGTE(FieldClassReviewID, v))
}

// ClassReviewIDLT applies the LT predicate on the "class_review_id" field.
func ClassReviewIDLT(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLT(FieldClassReviewID, v))
}

// ClassReviewIDLTE applies the LTE predicate on the "class_review_id" field.
func ClassReviewIDLTE(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLTE(FieldClassReviewID, v))
}

// ClassReviewIDContains applies the Contains predicate on the "class_review_id" field.
func ClassReviewIDContains(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldContains(FieldClassReviewID, v))
}

// ClassReviewIDHasPrefix applies the HasPrefix predicate on the "class_review_id" field.
func ClassReviewIDHasPrefix(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldHasPrefix(FieldClassReviewID, v))
}

// ClassReviewIDHasSuffix applies the HasSuffix predicate on the "class_review_id" field.
func ClassReviewIDHasSuffix(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldHasSuffix(FieldClassReviewID, v))
}

// ClassReviewIDEqualFold applies the EqualFold predicate on the "class_review_id" field.
func ClassReviewIDEqualFold(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEqualFold(FieldClassReviewID, v))
}

// ClassReviewIDContainsFold applies the ContainsFold predicate on the "class_review_id" field.
func ClassReviewIDContainsFold(v string) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldContainsFold(FieldClassReviewID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.ClassReviewLike {
	return predicate.ClassReviewLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClassReviews applies the HasEdge predicate on the "class_reviews" edge.
func HasClassReviews() predicate.ClassReviewLike {
	return predicate.ClassReviewLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClassReviewsTable, ClassReviewsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClassReviewsWith applies the HasEdge predicate on the "class_reviews" edge with a given conditions (other predicates).
func HasClassReviewsWith(preds ...predicate.ClassReview) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(func(s *sql.Selector) {
		step := newClassReviewsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClassReviewLike) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClassReviewLike) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClassReviewLike) predicate.ClassReviewLike {
	return predicate.ClassReviewLike(sql.NotPredicates(p))
}
