// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yudai2929/kendai-navi/backend/db/ent/classreviewlike"
	"github.com/yudai2929/kendai-navi/backend/db/ent/predicate"
)

// ClassReviewLikeDelete is the builder for deleting a ClassReviewLike entity.
type ClassReviewLikeDelete struct {
	config
	hooks    []Hook
	mutation *ClassReviewLikeMutation
}

// Where appends a list predicates to the ClassReviewLikeDelete builder.
func (crld *ClassReviewLikeDelete) Where(ps ...predicate.ClassReviewLike) *ClassReviewLikeDelete {
	crld.mutation.Where(ps...)
	return crld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (crld *ClassReviewLikeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, crld.sqlExec, crld.mutation, crld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (crld *ClassReviewLikeDelete) ExecX(ctx context.Context) int {
	n, err := crld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (crld *ClassReviewLikeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(classreviewlike.Table, sqlgraph.NewFieldSpec(classreviewlike.FieldID, field.TypeInt))
	if ps := crld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, crld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	crld.mutation.done = true
	return affected, err
}

// ClassReviewLikeDeleteOne is the builder for deleting a single ClassReviewLike entity.
type ClassReviewLikeDeleteOne struct {
	crld *ClassReviewLikeDelete
}

// Where appends a list predicates to the ClassReviewLikeDelete builder.
func (crldo *ClassReviewLikeDeleteOne) Where(ps ...predicate.ClassReviewLike) *ClassReviewLikeDeleteOne {
	crldo.crld.mutation.Where(ps...)
	return crldo
}

// Exec executes the deletion query.
func (crldo *ClassReviewLikeDeleteOne) Exec(ctx context.Context) error {
	n, err := crldo.crld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{classreviewlike.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (crldo *ClassReviewLikeDeleteOne) ExecX(ctx context.Context) {
	if err := crldo.Exec(ctx); err != nil {
		panic(err)
	}
}
