// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ClassReview is the predicate function for classreview builders.
type ClassReview func(*sql.Selector)

// ClassReviewLike is the predicate function for classreviewlike builders.
type ClassReviewLike func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
