-- Create "users" table
CREATE TABLE "users" ("id" character varying NOT NULL, "nickname" character varying NOT NULL, "firebase_uid" character varying NOT NULL, "email" character varying NOT NULL, "profile_image_url" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "user_email" to table: "users"
CREATE UNIQUE INDEX "user_email" ON "users" ("email");
-- Create "class_reviews" table
CREATE TABLE "class_reviews" ("id" character varying NOT NULL, "class_id" bigint NOT NULL, "teacher_id" bigint NOT NULL, "comment" character varying NOT NULL, "class_year" bigint NOT NULL, "term" bigint NOT NULL, "satisfaction_level" bigint NOT NULL, "easy_level" bigint NOT NULL, "attendance_method" bigint NOT NULL, "evaluation_method" bigint NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "user_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "class_reviews_users_class_reviews" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "classreview_class_id" to table: "class_reviews"
CREATE INDEX "classreview_class_id" ON "class_reviews" ("class_id");
-- Create index "classreview_user_id" to table: "class_reviews"
CREATE INDEX "classreview_user_id" ON "class_reviews" ("user_id");
-- Create "class_review_likes" table
CREATE TABLE "class_review_likes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "class_review_id" character varying NOT NULL, "user_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "class_review_likes_class_reviews_class_review_likes" FOREIGN KEY ("class_review_id") REFERENCES "class_reviews" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "class_review_likes_users_class_review_likes" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "classreviewlike_user_id_class_review_id" to table: "class_review_likes"
CREATE UNIQUE INDEX "classreviewlike_user_id_class_review_id" ON "class_review_likes" ("user_id", "class_review_id");
